import { describe, it, expect } from 'vitest';
import { generateNginxConfig, generateCSPHeader } from '../src/nginx';
import type { CSPDirectives } from '../src/types';

describe('nginx', () => {
  describe('generateCSPHeader', () => {
    it('generates default-src directive', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("default-src 'self'");
    });

    it('generates script-src with hashes', () => {
      const directives: Partial<CSPDirectives> = {
        'script-src': ["'self'", "'sha256-abc123'", "'sha256-def456'"]
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("script-src 'self' 'sha256-abc123' 'sha256-def456'");
    });

    it('generates style-src with hashes', () => {
      const directives: Partial<CSPDirectives> = {
        'style-src': ["'self'", "'sha256-xyz789'"]
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("style-src 'self' 'sha256-xyz789'");
    });

    it('generates multiple directives separated by semicolons', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"],
        'script-src': ["'self'"],
        'img-src': ["'self'", 'https:']
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("default-src 'self';");
      expect(result).toContain("script-src 'self';");
      expect(result).toContain("img-src 'self' https:");
    });

    it('includes external URLs in script-src', () => {
      const directives: Partial<CSPDirectives> = {
        'script-src': ["'self'", 'https://cdn.example.com']
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain('https://cdn.example.com');
    });

    it('includes font-src directive', () => {
      const directives: Partial<CSPDirectives> = {
        'font-src': ["'self'", 'https://fonts.gstatic.com']
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("font-src 'self' https://fonts.gstatic.com");
    });

    it('handles connect-src directive', () => {
      const directives: Partial<CSPDirectives> = {
        'connect-src': ["'self'", 'https://api.example.com']
      };

      const result = generateCSPHeader(directives);

      expect(result).toContain("connect-src 'self' https://api.example.com");
    });
  });

  describe('generateNginxConfig', () => {
    it('generates add_header directive', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateNginxConfig(directives);

      expect(result).toContain('add_header Content-Security-Policy');
    });

    it('wraps CSP value in quotes', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateNginxConfig(directives);

      expect(result).toMatch(/add_header Content-Security-Policy ".*" always;/);
    });

    it('includes always parameter', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateNginxConfig(directives);

      expect(result).toContain('always;');
    });

    it('includes comment header when enabled', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateNginxConfig(directives, { includeComments: true });

      expect(result).toContain('# Content-Security-Policy');
      expect(result).toContain('# Generated by gila-astro-csp');
    });

    it('excludes comments when disabled', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"]
      };

      const result = generateNginxConfig(directives, { includeComments: false });

      expect(result).not.toContain('#');
    });

    it('generates complete config with all directives', () => {
      const directives: Partial<CSPDirectives> = {
        'default-src': ["'self'"],
        'script-src': ["'self'", "'sha256-abc'"],
        'style-src': ["'self'", "'sha256-xyz'"],
        'img-src': ["'self'", 'data:', 'https:'],
        'font-src': ["'self'", 'https://fonts.gstatic.com'],
        'connect-src': ["'self'"],
        'frame-ancestors': ["'none'"],
        'form-action': ["'self'"],
        'base-uri': ["'self'"]
      };

      const result = generateNginxConfig(directives, { includeComments: false });

      expect(result).toContain('add_header Content-Security-Policy');
      expect(result).toContain("default-src 'self'");
      expect(result).toContain("script-src 'self' 'sha256-abc'");
      expect(result).toContain("frame-ancestors 'none'");
    });
  });
});
