import type { CSPDirectives, NginxOptions } from './types.js';

const DEFAULT_OPTIONS: Required<NginxOptions> = {
  outputPath: './dist/_csp/nginx.conf',
  includeComments: true
};

export function generateCSPHeader(directives: Partial<CSPDirectives>): string {
  const parts: string[] = [];

  const directiveOrder: (keyof CSPDirectives)[] = [
    'default-src',
    'script-src',
    'style-src',
    'img-src',
    'font-src',
    'connect-src',
    'frame-ancestors',
    'form-action',
    'base-uri'
  ];

  for (const directive of directiveOrder) {
    const values = directives[directive];
    if (values && values.length > 0) {
      parts.push(`${directive} ${values.join(' ')}`);
    }
  }

  return parts.join('; ');
}

export function generateNginxConfig(
  directives: Partial<CSPDirectives>,
  options?: Partial<NginxOptions>
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const cspHeader = generateCSPHeader(directives);

  const lines: string[] = [];

  if (opts.includeComments) {
    lines.push('# Content-Security-Policy Header');
    lines.push('# Generated by gila-astro-csp');
    lines.push('');
  }

  lines.push(`add_header Content-Security-Policy "${cspHeader}" always;`);

  return lines.join('\n');
}
